import type { ScanResult } from '@introspect/core-types';

export type ReportFormat = 'json' | 'markdown' | 'html';

export function generateReport(result: ScanResult, format: ReportFormat = 'markdown'): string {
  switch (format) {
    case 'json':
      return JSON.stringify(result, null, 2);
    case 'markdown':
      return generateMarkdown(result);
    case 'html':
      return generateHtml(result);
  }
}

function generateMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push(`# Introspect Scan Report: ${result.repoName}`);
  lines.push('');
  lines.push(`**Scanned:** ${result.scannedAt}`);
  lines.push(`**Files:** ${result.totalFiles} | **Lines:** ${result.totalLines.toLocaleString()} | **Languages:** ${result.languages.join(', ')}`);
  lines.push(`**Mode:** ${result.scanMode} | **Duration:** ${result.scanDurationMs}ms`);
  lines.push('');

  lines.push(`## Overall Score: ${result.overallScore}/100`);
  lines.push('');
  lines.push(result.summary);
  lines.push('');

  lines.push('## Category Scores');
  lines.push('');
  lines.push('| Category | Score |');
  lines.push('|----------|-------|');
  for (const [key, value] of Object.entries(result.scores)) {
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
    const emoji = value >= 80 ? '🟢' : value >= 60 ? '🟡' : '🔴';
    lines.push(`| ${emoji} ${label} | ${value}/100 |`);
  }
  lines.push('');

  if (result.issues.length > 0) {
    lines.push(`## Issues Found (${result.issues.length})`);
    lines.push('');

    const grouped = groupBy(result.issues, (i) => i.type);
    for (const [type, issues] of Object.entries(grouped)) {
      lines.push(`### ${type.toUpperCase()} (${issues.length})`);
      lines.push('');

      for (const issue of issues) {
        const location = issue.file ? `\`${issue.file}:${issue.line}\`` : '';
        lines.push(`- **[${issue.severity.toUpperCase()}]** ${issue.title} ${location}`);

        if (issue.badCode && issue.goodCode) {
          lines.push('  ```diff');
          lines.push(`  - ${issue.badCode}`);
          lines.push(`  + ${issue.goodCode}`);
          lines.push('  ```');
        }
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [Introspect](https://github.com/introspect/introspect)*');

  return lines.join('\n');
}

function generateHtml(result: ScanResult): string {
  // Phase 3 — for now, wrap markdown in basic HTML shell
  const md = generateMarkdown(result);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Introspect Report: ${result.repoName}</title>
  <style>body { font-family: system-ui; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }</style>
</head>
<body>
  <pre>${escapeHtml(md)}</pre>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function groupBy<T>(arr: T[], key: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const k = key(item);
    (result[k] ??= []).push(item);
  }
  return result;
}
